<a href="https://colab.research.google.com/github/kszymon/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Spis treści:
Podstawy

1.   [Podstawy](https://colab.research.google.com/drive/1qY6it9O0HHItgcTuztbJlmgXEt_VI4m-#scrollTo=mjJpDYcIKn7T&line=1&uniqifier=1)
2.   [Typy danych](https://https://colab.research.google.com/drive/1qY6it9O0HHItgcTuztbJlmgXEt_VI4m-#scrollTo=OGBolcLuJwYE)
3.   [Tworzenie tablic](https://https://colab.research.google.com/drive/1qY6it9O0HHItgcTuztbJlmgXEt_VI4m-#scrollTo=HycXb9TaJzVR)
4.   [Podstawowe operacje na tablicach](https://colab.research.google.com/drive/1qY6it9O0HHItgcTuztbJlmgXEt_VI4m-#scrollTo=EduyqyuZJzsB&line=1&uniqifier=1)
5.   [Generowanie liczb pseudolosowych](https://colab.research.google.com/drive/1qY6it9O0HHItgcTuztbJlmgXEt_VI4m-#scrollTo=LTjv3mltJzzY)
6.   [Podstawowe funkcje](https://https://colab.research.google.com/drive/1qY6it9O0HHItgcTuztbJlmgXEt_VI4m-#scrollTo=EduyqyuZJzsB&line=1&uniqifier=1)
7.   [Indeksowanie, Wycinanie](https://https://colab.research.google.com/drive/1qY6it9O0HHItgcTuztbJlmgXEt_VI4m-#scrollTo=V6m7a93yJz5J)
8.   [Iteracja po tablicach](https://https://colab.research.google.com/drive/1qY6it9O0HHItgcTuztbJlmgXEt_VI4m-#scrollTo=XIanu1SsJz7h&line=1&uniqifier=1)
9.   [Zmiana rozmiaru tablic](https://https://colab.research.google.com/drive/1qY6it9O0HHItgcTuztbJlmgXEt_VI4m-#scrollTo=BntTKnyLJz-L&line=1&uniqifier=1)
10.  [Maski logiczne](https://https://colab.research.google.com/drive/1qY6it9O0HHItgcTuztbJlmgXEt_VI4m-#scrollTo=3ShcsOiM5qce&line=1&uniqifier=1)


Podstawy

In [2]:
import numpy as np
np.__version__

'1.25.2'

In [3]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [5]:
x = np.array([1,5])
x

array([1, 5])

In [6]:
print(x)

[1 5]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [12]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [13]:
x.dtype

dtype('float64')

In [14]:
x = np.array([[1,2], [-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [15]:
x.ndim

2

In [16]:
x.shape

(2, 2)

In [17]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [18]:
x.shape

(2, 3)

In [19]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4,1,3],
      [4,2,1]],
     [[3, 2, 1],
      [4,3,2]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [20]:
x.ndim

3

In [21]:
x.shape

(3, 2, 3)

Typy danych

In [22]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [23]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [24]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [25]:
A = np.array([1,2,5],dtype='complex')
A.dtype

dtype('complex128')

In [26]:
A = np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype

dtype('int64')

In [27]:
A = np.array([False, True])
A.dtype

dtype('bool')

In [28]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

<ipython-input-28-27ab11b0e872>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 230 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([24, 120, 230], dtype=np.int8)


dtype('int8')

In [29]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

Tworzenie tablic



In [30]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.ones(shape=[5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.ones(shape=[5,5], dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.full(shape=(3,3), fill_value=4, dtype="int")

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [35]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(start = 5, stop =10)

array([5, 6, 7, 8, 9])

In [38]:
np.arange(start =100, stop = 10,step =-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [39]:
np.arange(start = 0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [40]:
np.linspace(start=0, stop=1, num = 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [41]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach



In [45]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [46]:
A + B

array([6, 0, 7, 4])

In [47]:
A-B

array([0, 2, 1, 0])

In [48]:
A*B

array([ 9, -1, 12,  4])

In [49]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [50]:
np.add(A,B)

array([6, 0, 7, 4])

In [51]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [52]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [53]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [54]:
A+3

array([6, 4, 7, 5])

In [55]:
2*A

array([6, 2, 8, 4])

In [56]:
A+3*B

array([12, -2, 13,  8])

In [57]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [58]:
X*Y

array([[6, 0],
       [2, 0]])

In [59]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [60]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [61]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [62]:
np.random.seed(0)

In [63]:
np.random.randn()

1.764052345967664

In [64]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [65]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [66]:
np.random.rand()

0.1965823616800535

In [67]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

Podstawowe funkcje

In [68]:
np.random.rand(10,2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [69]:
np.random.randint(10)

3

In [70]:
np.random.randint(low=10, high=101,size=10)

array([56, 52, 66, 70, 87, 40, 34, 12, 13, 23])

In [72]:
np.random.choice([4,2,1,3,5])

4

In [74]:
np.random.choice(['python','java', 'sql'])

'python'

In [75]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.random.shuffle(data)

In [77]:
data

array([6, 1, 5, 9, 4, 0, 7, 2, 8, 3])

Podstawowe funkcje

In [78]:
np.exp(1)

2.718281828459045

In [79]:
np.sqrt(9)

3.0

In [80]:
np.all([2,3,0])

False

In [82]:
np.any([0,0,0])

False

In [88]:
bool(1.3)

True

In [91]:
A = np.random.rand(5)
A

array([0.69253159, 0.72525428, 0.50132438, 0.95608363, 0.6439902 ])

In [92]:
np.argmax(A)

3

In [93]:
A[np.argmax(A)]

0.9560836347232239

In [94]:
np.argmin(A)

2

In [95]:
A[np.argmin(A)]

0.5013243819267023

In [97]:
np.argsort(A)

array([2, 4, 0, 1, 3])

In [99]:
np.max(A)

0.9560836347232239

In [100]:
np.min(A)

0.5013243819267023

In [101]:
np.mean(A)

0.7038368171553939

In [102]:
np.median(A)

0.6925315900777659

In [103]:
np.std(A)

0.14751805105732366

Indeksowanie, Wycianie

In [104]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [105]:
A[2]

2

In [106]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [107]:
A[:2]

array([0, 1])

In [108]:
A[[0,2]]

array([0, 2])

In [109]:
A[-1]

19

In [110]:
A[10:15]

array([10, 11, 12, 13, 14])

In [113]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [127]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [130]:
A[1,2]=14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [131]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [132]:
for row in A:
  print (row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [134]:
for row in A:
  print (row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [136]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [138]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [139]:
A.shape

(4, 5)

In [141]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [144]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [145]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [152]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [153]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [154]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [156]:
np.bitwise_and(A > -5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
np.bitwise_and(A > -5, A<5)

In [157]:
A[np.bitwise_and(A > -5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [158]:
np.bitwise_or(A< -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])