<a href="https://colab.research.google.com/github/kszymon/data-science-bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy

###Funkcje statystyczne

In [13]:
import numpy as np
np.__version__

'1.25.2'

In [14]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 12.00, 11.70, 12.20, 2000],
                  [12.20, 12.40, 11.20, 12.20, 1500]])
print(prince)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   12.    11.7   12.2 2000. ]
 [  12.2   12.4   11.2   12.2 1500. ]]


sum()

In [15]:
price.sum()

4646.1

In [16]:
price.sum(axis=0)

array([  37.1,   37.2,   34.8,   37. , 4500. ])

In [17]:
price.sum(axis=1)

array([1049.7, 2048.4, 1548. ])

In [18]:
np.sum(price)

4646.1

min()

In [20]:
np.min(price, axis=0)

array([  12.2,   12. ,   11.2,   12.2, 1000. ])

max()

In [21]:
np.max(price, axis=0)

array([  12.5,   12.8,   11.9,   12.6, 2000. ])

median()

In [22]:
np.median(price)

12.4

mean()

In [24]:
np.mean(price, axis=0)

array([  12.36666667,   12.4       ,   11.6       ,   12.33333333,
       1500.        ])

std()

In [27]:
np.std(price, axis=0)

array([1.24721913e-01, 3.26598632e-01, 2.94392029e-01, 1.88561808e-01,
       4.08248290e+02])

var()

In [28]:
np.var(price, axis=0)

array([1.55555556e-02, 1.06666667e-01, 8.66666667e-02, 3.55555556e-02,
       1.66666667e+05])